controller_list:
  - name: fake_whole_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
initial:  # Define initial robot poses.
  - group: whole_arm
    pose: left_hand
  - group: arm
    pose: left