# Logitech Attack3
axis_linear:  # Forward/Back
  x: 1
  y: 0
  z: 3
scale_linear:  
  x: 12.5
  y: 12.5
  z: 2.5
scale_linear_turbo: 
  x: 12.5
  y: 12.5
  z: 2.5

axis_angular:  # Left/Right
  x: 2
scale_angular:
  x: 12.5
scale_angular_turbo: 
  x: 12.5

enable_button: 7  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
